//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchCustomerBalance
    {
        public int ID { get; set; }
        public string s_dbname { get; set; }
        public int n_branch_id { get; set; }
        public string s_branch_name { get; set; }
        public string n_customer_balance { get; set; }
    }
}
