//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchesTreasureBalance
    {
        public int ID { get; set; }
        public string s_dbname { get; set; }
        public Nullable<int> n_branch_no { get; set; }
        public Nullable<int> n_cash_id { get; set; }
        public string s_cash_name { get; set; }
        public string n_treasure_balance { get; set; }
    }
}
