//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int n_CompId { get; set; }
        public string s_CompName { get; set; }
        public string s_CompNameEng { get; set; }
        public string s_dbName { get; set; }
    }
}
