//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ID { get; set; }
        public string s_dbname { get; set; }
        public Nullable<decimal> n_credit { get; set; }
        public Nullable<decimal> n_debit { get; set; }
        public string d_doc_date { get; set; }
        public string s_account_no { get; set; }
    }
}
